config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :subscriptions

  resources :events

  resources :comments do
  member do
    get "vote"
  end
end

  resources :alerts

  resources :categories

  resources :user_subs

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/user_sub.rb
class UserSub < ActiveRecord::Base
  belongs_to :user
  belongs_to :subscription
end

app/controllers/user_subs_controller.rb
class UserSubsController < ApplicationController
  before_action :set_user_sub, only: [:show, :edit, :update, :destroy]

  # GET /user_subs
  # GET /user_subs.json
  def index
    @user_subs = UserSub.all
  end

  # GET /user_subs/1
  # GET /user_subs/1.json
  def show
  end

  # GET /user_subs/new
  def new
    @user_sub = UserSub.new
  end

  # GET /user_subs/1/edit
  def edit
  end

  # POST /user_subs
  # POST /user_subs.json
  def create
    @user_sub = UserSub.new(user_sub_params)

    respond_to do |format|
      if @user_sub.save
        format.html { redirect_to @user_sub, notice: 'User sub was successfully created.' }
        format.json { render :show, status: :created, location: @user_sub }
      else
        format.html { render :new }
        format.json { render json: @user_sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_subs/1
  # PATCH/PUT /user_subs/1.json
  def update
    respond_to do |format|
      if @user_sub.update(user_sub_params)
        format.html { redirect_to @user_sub, notice: 'User sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_sub }
      else
        format.html { render :edit }
        format.json { render json: @user_sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_subs/1
  # DELETE /user_subs/1.json
  def destroy
    @user_sub.destroy
    respond_to do |format|
      format.html { redirect_to user_subs_url, notice: 'User sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_sub
      @user_sub = UserSub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_sub_params
      params.require(:user_sub).permit(:user_id, :subscription_id, :moderator)
    end
end

app/helpers/user_subs_helper.rb
module UserSubsHelper
end

app/views/user_subs/_form.html.erb
<%= form_for @user_sub, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :moderator, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :moderator, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  user_subs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/user_subs/edit.html.erb
<%- model_class = UserSub -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => UserSub %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_subs/index.html.erb
<%- model_class = UserSub -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserSub %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:moderator) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_subs.each do |user_sub| %>
      <tr>
        <td><%= user_sub.id %></td>
        <td><%= user_sub.moderator %></td>
        <td><%=l user_sub.created_at, format: :long %></td>
        <td>
          <%= link_to user_sub_path(user_sub), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to user_sub_path(user_sub), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_sub_path,
            :class => 'btn btn-primary' %>

app/views/user_subs/new.html.erb
<%- model_class = UserSub -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => UserSub %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_subs/show.html.erb
<%- model_class = UserSub -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserSub %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:moderator) %></dt>
      <dd><pre class="prettyprint"><%= @user_sub.moderator %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_subs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_sub_path(@user_sub), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_sub_path(@user_sub),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>